### ISSUE TITLE
 Linha de Transmissão de Microfita

### ISSUE THREAD

**Issue by kathleenrego** [JeffersonHS/LinesProject#1]
### Desenvolva um programa computacional que projete uma linha de transmissão em microfita que possua tais entradas:

- [x] impedância característica

- [x] espessura do substrato (em centímetros)

- [x] altura (em centímetros) do substrato disponíveis comercialmente

- [x] permissividade

###  Determinar:

- [x] a espessura W da linha
- [x] o comprimento de onda guiado

### Considere também que a tangente de perdas do material é obtida a partir de valores obtidos de gráficos disponíveis na literatura, assim determine:

- [x] atenuação devido ao dielétrico

- [x] ambiente computacional em janelas

**Comment by JeffersonHS** [comment]
@kathleenrego O programa já está pronto, apenas aguardando a lista das espessuras comerciais para o substrato.
